<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4aqht05\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4aqht05/appProdProjectContainer.php') {
    touch(__DIR__.'/Container4aqht05.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container4aqht05\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container4aqht05\appProdProjectContainer([
    'container.build_hash' => '4aqht05',
    'container.build_id' => '120ec375',
    'container.build_time' => 1555409493,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4aqht05');
